import type { Metadata } from "next";
import "./globals.css";
import "./token.css";

import localFont from "next/font/local";
//import { Roboto } from 'next/font/google'
import { ThemeProvider } from "./ThemeProvider";
import Navbar from "./Navbar";

import { Theme, Container } from "@radix-ui/themes";

import MenuToggleProvider from "./components/MenuToggleProvider";

import AppWrapper from "./components/AppWrapper";
import Overlay from "./components/Overlay";

// const roboto = Roboto({
//   subsets: ['latin'],
//   variable: '--font-roboto',
//   weight: ['400', '500']
// })

const poppins = localFont({
  src: "./fonts/poppins-regular-webfont.woff2",
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body className={poppins.variable}>
        <ThemeProvider attribute="class" disableTransitionOnChange>
          <Theme accentColor="crimson" panelBackground="solid" radius="full">
            <MenuToggleProvider>
              <div className="relative left-0 top-0 w-full h-screen">
                
                  <div
                    style={{
                      width: "100%",
                      borderEndStartRadius: "50%",
                      borderEndEndRadius: "50%",
                      height: "20vh",
                      zIndex: "1",
                    }}
                    className="dark:bg-black fixed"
                  ></div>
                  <div
                    className="dark:bg-black"
                    style={{
                      position: "fixed",
                      height: "25vh",
                      zIndex: "2",
                      width: "100%",
                      bottom: "0",
                      left: "0",
                    }}
                  ></div>

                  <div
                    style={{
                      position: "fixed",
                      top: "0",
                      left: "0",
                      height: "100vh",
                      zIndex: "3",
                      width: "100%",
                    }}
                  ></div>

                    <div
                      className="dark:bg-bg_color fixed"
                      style={{
                        marginBottom: "0px",
                        marginTop: "45vh",
                        width: "50%",
                        zIndex: "4",
                        borderBottomLeftRadius: "50%",
                        borderBottomRightRadius: "50%",
                        height: "40vh",
                      }}
                    ></div>
                    <div
                      className="dark:bg-black "
                      style={{
                        width: "55%",
                        position: "fixed",
                        bottom: "0",
                        right: "0",
                        float: "right",
                        height: "35vh",
                        borderTopLeftRadius: "50%",
                        borderTopRightRadius: "50%",
                        zIndex: '5'
                      }}
                    ></div>
                  
                  <div>
                    <div
                      style={{
                        position: "fixed",
                        left: "0",
                        top: "0",
                        zIndex: "7",
                        fontSize: "1.rem",
                        backgroundColor: "#01031",
                      }}
                      className="w-full "
                    ></div>
                  </div>

                  


                      <div >

                        <AppWrapper>
                        <Navbar />
                          
                          
                        <Container style={{ width: "100%", position: 'relative', zIndex: '8' }}
                    className="relative  w-full">
                          {children}
                        </Container>
                          
                        <Overlay />
                          </AppWrapper>
                      </div>
                    </div>
                  
                
              
            </MenuToggleProvider>
          </Theme>
        </ThemeProvider>
      </body>
    </html>
  );
}
{
  /* px-6 md:px-8 */
}
